spring:
  profiles:
    active: core

---

server:
  port: 8080
spring:
  profiles: core
  datasource:
    url: 'jdbc:mariadb://localhost:33060/gb5'
    username: root
    password: ${env.MYSQL_PASSWORD}
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.MariaDB103Dialect'
    generate-ddl: true
    show-sql: true

---

server:
  port: 9090
spring:
  profiles: deploy
  datasource:
    url: 'jdbc:mysql://mariadb:3306/gb5'
