server:
  port: 8080
spring:
  profiles:
    active: default
  datasource:
    url: 'jdbc:mysql://mariadb:3306/gb5'
    username: 'root'
    password: ${MYSQL_PASSWORD}
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.MariaDB103Dialect'
    generate-ddl: true
    show-sql: true
